---
title: Soulara Blog
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  category:
    output: true
defaults:
- scope:
    path: ''
    type: blog
  values:
    layout: post
    permalink: "/blog/:title/"
    Main Image: "/assets/placeholder.png"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: category
  values:
    layout: category
permalink: pretty
